"""
Multi-Model Intelligent Router & Fallback Engine
------------------------------------------------
Provides API-first model routing across Google Gemini, OpenAI, and Anthropic.
Features automatic retry, fallback hierarchy, latency monitoring, and token tracking integration.
"""

import time
from typing import Dict, Any, Optional, List
from pydantic import BaseModel
from governance.token_calculator import CostGovernanceCalculator, TokenUsageReport


class ModelRouterResponse(BaseModel):
    provider_used: str
    model_name: str
    output_text: str
    latency_seconds: float
    token_usage: TokenUsageReport
    fallback_occurred: bool


class IntelligentModelRouter:
    """Routes requests to primary model with automated failover and cost tracking."""

    def __init__(self, primary_provider: str = "gemini", primary_model: str = "gemini-1.5-flash"):
        self.primary_provider = primary_provider
        self.primary_model = primary_model
        self.fallback_chain = [
            {"provider": "gemini", "model": "gemini-1.5-flash"},
            {"provider": "openai", "model": "gpt-4o-mini"},
            {"provider": "anthropic", "model": "claude-3-5-sonnet"}
        ]

    def generate_completion(
        self,
        client_id: str,
        system_prompt: str,
        user_prompt: str,
        simulated_failure: bool = False
    ) -> ModelRouterResponse:
        """Executes LLM inference with automatic provider failover and governance tracking."""
        start_time = time.time()
        fallback_occurred = False

        for idx, config in enumerate(self.fallback_chain):
            provider = config["provider"]
            model = config["model"]

            # Simulate primary provider outage if requested for testing failover logic
            if simulated_failure and idx == 0:
                print(f"[ModelRouter Warning] Provider '{provider}/{model}' unreachable (Simulated Outage). Trying fallback...")
                fallback_occurred = True
                continue

            try:
                # Simulated completion output (In production, invokes provider SDK)
                output_text = (
                    f"[[Response generated by {provider.upper()} ({model})]]\n"
                    f"Analysis for client '{client_id}': High potential lead. Recommended AI Solution: "
                    f"Automated Lead Capture & Quickbooks Billing Integration."
                )

                # Estimate tokens (approx 4 chars per token)
                prompt_tokens = len(system_prompt + user_prompt) // 4
                completion_tokens = len(output_text) // 4

                token_report = CostGovernanceCalculator.calculate_request_cost(
                    client_id=client_id,
                    model_name=model,
                    prompt_tokens=prompt_tokens,
                    completion_tokens=completion_tokens
                )

                latency = time.time() - start_time

                return ModelRouterResponse(
                    provider_used=provider,
                    model_name=model,
                    output_text=output_text,
                    latency_seconds=round(latency, 4),
                    token_usage=token_report,
                    fallback_occurred=fallback_occurred
                )

            except Exception as e:
                print(f"[ModelRouter Error] Failed with {provider}/{model}: {str(e)}")
                fallback_occurred = True

        raise RuntimeError("All model providers in fallback chain failed.")


if __name__ == "__main__":
    router = IntelligentModelRouter()
    print("--- Primary Model Provider Execution ---")
    resp = router.generate_completion(
        client_id="client_ez_01",
        system_prompt="You are EZMarketing's Lead Intake Agent.",
        user_prompt="Evaluate inbound inquiry for plumbing repair business."
    )
    print(resp.model_dump_json(indent=2))

    print("\n--- Fallback Execution (Simulated Outage) ---")
    resp_fallback = router.generate_completion(
        client_id="client_ez_01",
        system_prompt="You are EZMarketing's Lead Intake Agent.",
        user_prompt="Evaluate inbound inquiry for plumbing repair business.",
        simulated_failure=True
    )
    print(resp_fallback.model_dump_json(indent=2))
